spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://ShaoxiongDu.mysql.rds.aliyuncs.com:3306/blog?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: DSXdsx05117218
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

logging:
  level:
    root: error
    com.lrm: error
  file: log/blog.log



